name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run:  echo Hello world
      
    - name: Eyyyyyy
      run: echo Helloworld
